// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: "2025-07-15",
  // SPA: the admin console is behind Keycloak (client-side OIDC) and is served
  // statically. This avoids SSR/Keycloak pitfalls.
  ssr: false,
  devtools: { enabled: true },
  runtimeConfig: {
    public: {
      apiBase: process.env.NUXT_PUBLIC_API_BASE || "http://localhost:3000/api/v1",
      keycloakUrl: process.env.NUXT_PUBLIC_KEYCLOAK_URL || "",
      keycloakRealm: process.env.NUXT_PUBLIC_KEYCLOAK_REALM || "",
      keycloakClientId: process.env.NUXT_PUBLIC_KEYCLOAK_CLIENT_ID || "travelnest-admin",
      keycloakSilentCheckSsoRedirectUri:
        process.env.NUXT_PUBLIC_KEYCLOAK_SILENT_CHECK_SSO_REDIRECT_URI || "",
    },
  },
  modules: [
    "@element-plus/nuxt",
    "@nuxt/eslint",
    "@pinia/nuxt",
    "@nuxtjs/tailwindcss",
    "@nuxt/test-utils/module",
  ],
  elementPlus: {
    /** Options */
  },
  pinia: {
    storesDirs: ["stores"],
  },
  tailwindcss: {
    exposeConfig: true,
    viewer: true,
    // and more...
  },
  vite: {
    server: {
      watch: {
        usePolling: false,
        ignored: [
          // Ignore files that are not in use, such as .gitignore
          "**/!(.gitignore)",
          // Ignore files that are generated by Nuxt
          "**/@(.output|node_modules|.nuxt|dist)",
        ],
      },
    },
  },
  devServer: {
    port: 8000,
  },
});
