apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  annotations:
    # Never let an automated sync prune these stateful, data-holding objects.
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
