apiVersion: v1
kind: Secret
metadata:
    name: worker-secret
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:2Vs5yEHWyxvCG1zvUD211A==,iv:FrS4onFqO31+HN3uprWZdsXiSqlgcfGGOjwxWS6ak/o=,tag:RApVO4QLedA1WbkU3hUCcQ==,type:str]
    MONGODB_URI: ENC[AES256_GCM,data:YV8Md9mML6KlKX6hNnw3gv4YQkdTW2OzGqxAcjspN0Z6zo8A1PLR7O+DgvE=,iv:OI9oPKJlK1WIQON64YF1XMIGZIiHxNglQMtJ9Ce5vaE=,tag:FznQLjBOohd4Sg4xojCpgQ==,type:str]
    ELASTICSEARCH_ENDPOINT: ENC[AES256_GCM,data:dIba8+YRTbOSfSoPkW+1DSRnuVrCZQmZHQ==,iv:Hhx8le2wbqYLRrmYLBwsteskdhAHhu+YfNO3hIxvP9M=,tag:R1++BEERANqVHwdajUE2yQ==,type:str]
    ELASTICSEARCH_HOSTS: ENC[AES256_GCM,data:ntC22ZOCFZQRBqpLUrNmR/BUHYkC/wizeg==,iv:2PfQbnTjesrKvfKEO5Xu5DuTzR7Lwgai5g99nJ40k9w=,tag:/Qr5XOC9zet0WHjm2nDO0Q==,type:str]
    ELASTICSEARCH_API_KEY: ENC[AES256_GCM,data:fjsbEVRAzNVHmk7a0aVP4A==,iv:b/qHWovhxgDkvGC1qf9Dy9QeRf/J+70h4kv2XZwS040=,tag:9YNDsDj97CGn8O3uGTRdRw==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:PILclFz8l0/hdg==,iv:3m/UBcIjW1ltB24WxDOs1TMibSCzIpJTmElwSmSI3QY=,tag:SpkDwvBBR7t541bJ73B+/A==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:s8qtqfzddw61ZrJ/tqYJB22Iyz68pg==,iv:WB2R41CnbnVvVRCXZJiF6QLXxO4Asx6JZpZaUjuRlv0=,tag:oA77u4Jg4FzmqEZRSKTY3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvOWRiWms2d0s1UmtrcVVs
            RUpNUjROb3BCOXBMbGV6c0VkcFJ6MU1IK2lvCjdIelpDMUo4bjUyQTljbU1WMHJr
            ejBmSXd0ZUFFTUduaTVCQkY4MDRBWW8KLS0tIFEyM3lwN3N3L2poM1VVU1FIZWJE
            c2kyMEFhOEVrTEcrTFd0WmZCVjZwRGMKwI4jP/iAp+R1wIGPs5DNIw6p6cIVPVyT
            a+KThX+9IrTnGtwrKAC/U2d+f8+XIm9BVy+s7HPlLkEZ0/0RqHqHoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1slytfaf55d75qg2yfeehd8eycd5gewtw370ved303g6zqeesgcrsl5uu8t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T11:59:04Z"
    mac: ENC[AES256_GCM,data:1YWHEYff0PKfkq40kJLSXvVtocPDT/1hOGTKxhSh1flu9P+p6Zk+us6qn+bdvSeEwjuaZJnaWoN19cL0JzkiQrgzSBW/eeSEGCmsf/AnCRMfn+Z+G1o5TBvaIavNYu9mwjbblvIuNJ9TokVpjyHiYfjqUXPNouh9pFr7ayQsiyk=,iv:SoTAnjZygL96KuhYbQeIsfrGWjwtLJA+dIDtlngKJvU=,tag:pwQVoZpZqKEhcHzXRnhaTQ==,type:str]
    version: 3.13.3
