apiVersion: v1
kind: Secret
metadata:
    name: worker-secret
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:tJ1xk4aHjRIBwIJQ48blaA==,iv:L6QaSC6GAUFlWgEWhl4RKM7a8Rm0RQRQEA1FIMLOA6U=,tag:v8+V3To21sTKYCZ9JZ3bWg==,type:str]
    MONGODB_URI: ENC[AES256_GCM,data:25VDfT8UtqvTy2qRQUGcnbvgsC5nkIOlr7KM29L39fuaWW4RtFPUB4hfesE=,iv:I9JqUhm6q9aIey0otTP3GQi1ev++VNV5VzFuHXn44Ak=,tag:B2ii/7EH4RKPQjQZdt3ocw==,type:str]
    ELASTICSEARCH_ENDPOINT: ENC[AES256_GCM,data:HLiuoX/UmKSmbItPxaef6JW091ClfdCIqQ==,iv:0QYozs9BeAjdDi881iIdJkcCIn7eA3ax/dSxH1CInGE=,tag:xm+tSxHnZHu1SytjBk0MvQ==,type:str]
    ELASTICSEARCH_HOSTS: ENC[AES256_GCM,data:iPLh5gaRTHNHYcv1nr4sbzibORWxUhdUNg==,iv:gibdCQTcQyUjjyOlJtADuMukdkXKHjd1xe9VRK9JLXk=,tag:hFZhNLsTsRKwG7rUZLqvFQ==,type:str]
    ELASTICSEARCH_API_KEY: null
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:lHQRly6JDym2Wg==,iv:K8fYK3ws7lCVut6VWfoXNZr7y6J7z9ljWn4oQTTBgNA=,tag:WzoC2YGOIllNcXA2R9Kc3A==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:UIb9Fm/3pHDi3qLeYTNFKHFLNPDX5A==,iv:vUvp/PJCX2xqSEZs3Kmnz765MF7erulLf41dgdxSDxk=,tag:S+JCK9aTXrnzcc2HwRbIdQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjS3FDY3kzYms5Y0Zjdk9v
            eklHenZUbVRqQ2ZrMHRFdWhLUU1CUXlNOVNnCjZUdnU5ellEM2ZjQ3dFYzNYYW1E
            bC9Ha3g0R2p2dGYrV3RleTBMNE1mYXMKLS0tIG1PYnppR29FMzVqdVFpQjZENVdK
            RThrMnlEa2xMejFRc2V3TjBPQkJ4ZlUKk//Jy3JrvwvfqiMMNr9AnQzejqpuwbi9
            B6PV/LCExBTjrgnui+ZHsaJVMutcr6ScuG0Nm+uLT5aLnJTuXsVFrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1slytfaf55d75qg2yfeehd8eycd5gewtw370ved303g6zqeesgcrsl5uu8t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T12:50:27Z"
    mac: ENC[AES256_GCM,data:nqCo+i36bzZih+oHsLeRsN5cM2jdxu1QSw1MpSPm1m1+5MMLaKKjry9KwFEa+NTW1l3mEQVcMDXTcSG/2pvVgM797GQmqJnp13aFfLTPSyw7hHl0N0Qnp1PXGNxBoG+5Not2mLQmXxwEbaxl7I/D9ooX7AWrTUfMfehXfSRrnSY=,iv:nbhEdERjNt0hz3+6hUATfG2TvqG2OY0I4xu+HkQqij0=,tag:u6WYuXEmTsSFQtpfNiVr/Q==,type:str]
    version: 3.13.3
