apiVersion: v1
kind: Secret
metadata:
  name: worker-secret
type: Opaque
stringData:
  DB_PASSWORD: ${DB_PASSWORD}
  MONGODB_URI: ${MONGODB_URI}
  ELASTICSEARCH_ENDPOINT: ${ELASTICSEARCH_ENDPOINT}
  ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HOSTS}
  ELASTICSEARCH_API_KEY: ${ELASTICSEARCH_API_KEY}
  MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
  MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
