apiVersion: v1
kind: Secret
metadata:
    name: media-secret
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:VGkCUivznenqn1JyN+obRg==,iv:LmSo3XSCawryoB0LfvKc8T8ZHUTLnCqDq8W60s7yvkk=,tag:9hzLwTpWHgQi3mqCCDETCA==,type:str]
    MYSQL_DSN: ENC[AES256_GCM,data:Iw716z6H+86VXHzrCIGMFM/hi+RElZIhLtbAfTYrUGoYZx0cyNciE5cVnTI8FCrrzqocCjY44k0THVeVP/+lczOSXyQb,iv:phRiSyw4gnKAuv5jnmSoSArVnkTxM2L4YoJYffCYDv0=,tag:KsGr5wVJ3JnSlumOy35FIA==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:FPiPQbu6vPSmMw==,iv:dOb60yYpbgRBtyNVR0fNfUHvx7HtYH0dhMKeXi7oink=,tag:5oEFFFggkoRloCRWuOc+fA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:GHjmB1eNHm3kG2eP3DRhck0DdA+yVA==,iv:M+LC7uUxWIS/4EiJCMOwTuqx8LwgrVM0Wid62qss5Nc=,tag:dSxq5h6KKTptzIB7iaxthA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSVU5TGVTKzNBNEVZRDJX
            a2pCSXcxT1N0YWlRSExjdWhnYlRWS0ZZZTBjCjR0cWdacHczNCs5UVBoZk9TSDQz
            QUI2NTdOeFZONUh6UG5WVEJLVHBFeFEKLS0tIGp3SW5QOWg4aUxZSWgxRUNnTUFr
            SXBsRFc0V3pncVpFbjFtNU9hQzZjbE0KSzYDd7hMVlNxEUiKzKamMCONW3ifi5Fk
            ng1Xx1RwXc6Rf7ehROW6rkvMNDriHQ5vrfcJZoADPHtq0SHnFnu+Zw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1slytfaf55d75qg2yfeehd8eycd5gewtw370ved303g6zqeesgcrsl5uu8t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T12:50:27Z"
    mac: ENC[AES256_GCM,data:li1/pIv3EcIFuCKxNdxAOkMS58olR9Zm5bvnupZPOPxd4wnMMPyzfkngt7UrsIpK25F7IvnEZTuhbC9p2S0kKsEOpWDCnxHMR3RAnydRZaoH8CuHCWbLbcE/RWP9vY3JpybuFC9wCP1Glpg5nHmQGQhvzyDCoU954pP7P/pIaZs=,iv:t4wwChHAliL3sXb4CS8fCmLL0J6TT22um2jpjI0fu08=,tag:rkbXhOqFMv+icJPY0uQlHA==,type:str]
    version: 3.13.3
