apiVersion: v1
kind: Secret
metadata:
    name: media-secret
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:34EMnWE5f3RD57heIsM8JA==,iv:tXi0WreyLXRNM+Y04Fskf0alBZkA5Y2GhexyO+un5Qk=,tag:Ni0zEZy4EjbQt0WasWjazQ==,type:str]
    MYSQL_DSN: ENC[AES256_GCM,data:jx+jpmvCvdBDdvz3pNPPsMmlcvdQzHr+8zMOB6UVN/lF82gxBmKs6rSjqwCxBzyNnusHce+FH4cCL6i2JQGWiTsXn2dO,iv:GQj8cixGwOjNPZZRDRE79U+2jNC6HNIo/7SllAEtzTA=,tag:Tcw5AAVQa+13MsBssRj9Qw==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:mLxsDgnyEfom9A==,iv:Ombs1hewO+gdC1/981b6tD3Czbq87eaIB9+L1DKgEaE=,tag:Q/vnQzaU6O9LVyZoa72ptg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:D5buiGgCpO6y6Anxhdg/IPDdVHGegg==,iv:eEATTH5lW/+kAryc3KYy3ejSsNzBgkYPaGjWJ7o+xVs=,tag:6ypLlvQNk2qoUevOILc93w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZTcwdVk1MXZEZWtQMExZ
            ZmNyOFBxT3hGSlV4ajByeVlOY3AzQ245b3hVCitBbHpqeVZER3hjWU53M2NkS2Fy
            ZkFSZVZ2eDQzcDFucittRytZcWV1Z3cKLS0tIGJaaGt1Y3hWVDFraUxNaEJXYkR2
            UjNxZmE4UnJiY3I5TTFZOVoyMm8wMEUKr9DarcLIaqU2PlkRgymHxtpqawxB5Uzx
            wcK2lQmrpINIKi5/6ntiyn6qiJ1ONIxur+MNDaD09fVG+UnP9KmepQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1slytfaf55d75qg2yfeehd8eycd5gewtw370ved303g6zqeesgcrsl5uu8t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T11:59:04Z"
    mac: ENC[AES256_GCM,data:98E5bCsVphOxwU9eFM6BSDL2Sxn9dJPxpW0knjo9Y8xS4YmbyLsWcEy7nbcxj3f+uxdXJsSwv2W0Ayzjc22jeEk9dhs2zoXHshfKvHss9Tp4rDDhBbKmPFHih+oi5BhNo/nt0oVrbR4/FYf8aciZyHdOErzixb3pcgnRX6yNrsc=,iv:eAzpRq1j2sEu/Ns7kDPc0G6rxUMBolrI6GgsoFtrj4A=,tag:nDqauadxzjKipOhn8xTghg==,type:str]
    version: 3.13.3
