apiVersion: v1
kind: Secret
metadata:
  name: media-secret
type: Opaque
stringData:
  DB_PASSWORD: ${DB_PASSWORD}
  MYSQL_DSN: travelnest:${DB_PASSWORD}@tcp(mysql:3306)/travelnest?parseTime=true
  MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
  MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
