apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:6q6G37zNAVh6FNRu/4Y63Q==,iv:MJw/jOIGYHdhiEAO6BN0fqcc3c3stoas8vorQkINO5Y=,tag:WbBtYPk4Lmz31xzfiqGxxA==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:1G7ixYNYWGIyFxs3socgqQ==,iv:xG9gOimh48RTcBwGZxov8rsoIjIg0d7xF5JXfUJJTTY=,tag:3oEIGsEXpwLJg/LGrA3qQw==,type:str]
    KEYCLOAK_DB_PASSWORD: ENC[AES256_GCM,data:ZKcomwwIGOnEFrwZkpvVfQ==,iv:BsYpbYX7VTZZ+JqOCFPUsHGvP0KZkVbHOstTcKSLcKs=,tag:+kC/r0PBzidOJ1DH8ymzSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbjMrS0RXTFhIdUd5ZWxn
            VWFYdWdwK3MrMkRsYzdWQ1VBdmx5Q2tKM1VrCmhobllFdVNuQlc2dDg3b2JqSUVx
            VWllQ0h4V2E0ampzeG5pNjYrazZmUzAKLS0tIDBaRjhodlo2ck52aFNzNk5hL3ZX
            MzV3YWc4VFJVMU1EWUI2enlmSy9XaDQK0iCzqivKVCx7b8fit4+B0iZyP3vglruW
            NChkpuWtnd3LNOPTp+3fkHlmSaYSQXMyNz4853N9gTKX8+m/94Oyew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1slytfaf55d75qg2yfeehd8eycd5gewtw370ved303g6zqeesgcrsl5uu8t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T12:50:27Z"
    mac: ENC[AES256_GCM,data:1tAUrvbfr5ifbw8455uNw4YrCpp74Kvqag7bDmLU1ivAzIi7m2vCYSNZnn7NftW14R/mv6AjB7fTJCp0adM89ChkF2UvQAMHbDLZCkfoFyWvKlWhSElugp1Au6Ews0iPwWQFXH2K1U84uRTmb0zMp5RjuasGXsanc0l4Y7c7PKc=,iv:G40FH5C3SBFmZ1FLvrAPDzmIRp4WYs7kGn2c05d2pAw=,tag:1jpyks6Zgech9IiUibZL4A==,type:str]
    version: 3.13.3
