apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:YN6xz5pyMGIi+Bhz4pcYug==,iv:Ydy7PiEEW7vIcqrx/yW6IINU0gzDXaY9ytpbAhtPF08=,tag:3DGLYtAIy0m4OzYEDHZUCQ==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:V9I/l53ngO5aQIDILC6AKw==,iv:XdRyWA5pkSaFskosAX00b2oYKjUcCrbeWfz6Tf/pwUY=,tag:hlTCJ5zx+1gWBG6LyR2Xvw==,type:str]
    KEYCLOAK_DB_PASSWORD: ENC[AES256_GCM,data:r2FafRJl9nW20NTUBR0bWw==,iv:PNte0vuyApEOnpkMLUevtySr+alcQPWJhdbgoN1fTNo=,tag:f8MfB7lpMYBAP/LVq1CGfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZ25odEdKUjNKSVoxNVNp
            UGpTdVNxOHNCQWgranhybVpXQmhDS1d2VlUwCmRiYWlRL1BQbDFpSTlrTnJlSlQ2
            NDVKVFFNYk5aVmo3RmdyeEw2NEN1aU0KLS0tIDV3K1J3c01LTkxTOEFjbG5uZHFa
            SUhzYkpwQzVJVWlaRGN4b2hqZ2p2UGcKXGLbvkpkJl0z3hNicNKDJK3embHe9ppk
            KsnzhGBiiuCNm+ZMObKzO+mSczLVYMYzj/iV9UmgFLzHY+boW/iKoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1slytfaf55d75qg2yfeehd8eycd5gewtw370ved303g6zqeesgcrsl5uu8t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T11:59:04Z"
    mac: ENC[AES256_GCM,data:c0MR2dsdLLxkb9w0/OBoBEjHfVcHklGo/4/hLFQDszCm1v6NwSWIIOJFjKbVF94r9LkjkjkE8HQoGiQym5zs8KVYbid1LsRcRnqXH4TLw06EMlWAaXfS0OoqqPUyFQbbj4HawJ3L99IOpTmC7joL3FRf20PtXSWwv4kE9FR55bI=,iv:iB9sK00pPNa3pirOJInoflRpfVucCy4CpzlT/6wud3A=,tag:bGP01IdRqBrC93PZj0rN4A==,type:str]
    version: 3.13.3
