apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: travelnest
resources:
  - ../../base
  - configmap.yaml
  - secret.yaml
images:
  - name: travelnest-analytics
    newName: docker.io/leducphuong/travelnest-analytics
    newTag: latest
