apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: travelnest-local-infra
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: travelnest-local
spec:
  project: default
  source:
    repoURL: https://github.com/bk-leducphuong/TravelNest-Hotel_Booking_System.git
    targetRevision: develop
    path: deploy/k8s/local/infra
  destination:
    server: https://kubernetes.default.svc
    namespace: travelnest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
