apiVersion: v1
kind: Secret
metadata:
    name: analytics-secret
type: Opaque
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:9nztBs21HMcDLWHqwkxRo8yCDCTwIgaO+JL+bbsL9428nCtMAplX2fd3/D8=,iv:XrcaNA129UuV0Pu9TShUHvbGo6CTEZ3jH7pRkRxFhoU=,tag:2SJ2vswwJR2gj+3od9OsEw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MU9OandRM1lWcDgyUHdn
            Y0FkVDNvU08zYkNFbGJsQ3Q5Uk5QTWhhMGxrCnlTV2hiOUpBd0V2dTRCMWpuRTAy
            Y3lSbWx4c0o4NHIwQUZNTmNBVUFMa2MKLS0tIFp5anhHaDhWcGk5c29iOXl4UFpP
            dk03UHpSTUw1bnR1dlgzYWNaZWI5OEkK7rD9QeYegh/aBRvcdry5KoIiI6cOKDRd
            7Q3JTmW+VIbj5/yq2pfvPw3SAmPQMj9CgWNM9jJDKGT0QtXWt3az3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1slytfaf55d75qg2yfeehd8eycd5gewtw370ved303g6zqeesgcrsl5uu8t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T11:59:03Z"
    mac: ENC[AES256_GCM,data:z1Un2YKroECYlFKdcbbYVpPxmBNwfMOqn08poXIgfd4plkqdxhnfUe+wdetiVe9eonw+gGOUrla+9QiRmVmSBHYButA3dx4lzmI23KgZnpcqWCiEAdZ6IZTsUxXLpHXuZVCOSqo11+30wBaOloS93Vd9qOIrNSK/TjYVNIu952g=,iv:KRDkEBOl8TdoBVYCtwsx19tIFhe6EZ3Bu/otvsXzSHs=,tag:pd+1fb962gF3xrxU7fX4HA==,type:str]
    version: 3.13.3
