apiVersion: v1
kind: Secret
metadata:
    name: analytics-secret
type: Opaque
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:lpVvKVVjMceE83jBCDYZZcA5+e6DwOQeocj9p/2opSKrtM5jn6ivCJ2UxfY=,iv:2qU1BttX99O+XQgunK9zvaLFfXZcYVt8E7FxfvpYFKg=,tag:GqdN95GfOjumGmgC75epRQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBra3lQVmhKdmJER2N5anoy
            aitLcHdnMEpwMlhnVUdwTGtqcDliaFNiNnljCmRvU0U4aU0rbWU0bnZiZW1NTjJV
            YVRqeG9YajUxSE5zSjR0REkwUisxS2cKLS0tIHRWVEpRTmoyUjdFV1grZ0RnakIr
            RXhBNi9Qbk5JeDhnSXhzZkFxbW16ZTgKHYkttLjJpT2lXJdo9k9apzhPwmUXjbZq
            cYJvzZzmf7snsi3/K3RVz852o6UUaojMHjNaX5xXTaSY4EVrrriRew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1slytfaf55d75qg2yfeehd8eycd5gewtw370ved303g6zqeesgcrsl5uu8t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T12:50:27Z"
    mac: ENC[AES256_GCM,data:2S2X2EtTHJmL3dZDHHBJ4RyXOuIucp5VxEtvOOrwruh8eFjEtPBpJmCa3iPgX0X624J2xrjam7hiGN7RDyWguJXxFT6d9SowmVBe9YzZTplMQypPeEhHEltoKqhjU70Yzw+ZmLPA0nfttttIv0zoMTIUtwm5uyXt5SmgCnjPH54=,iv:SORovKQppdEmJf+WehSln+xvqcRXHbgi4usSSG4bOm4=,tag:+dHrFiRdHasMfjLH0FLgrg==,type:str]
    version: 3.13.3
