apiVersion: v1
kind: Secret
metadata:
    name: api-secret
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:11fcS/6ns2J7olRicgRwqw==,iv:WV1tooKeQDkz3Dd9RZuBVewTlfIUEjNZu85iqx3D5G4=,tag:UvpEDv51gX5KGEBPDZHnjQ==,type:str]
    MONGODB_URI: ENC[AES256_GCM,data:1xy1NTpfKwf9p1LjyOeIlqZjOPhMZaof444n2Jz8f+qDkYMpXfAInpYtPCI=,iv:IuLdHFo0ejW/3+50/g2wscqvvtYz9ERI2mOiLRMAcc4=,tag:fs6U0KH/mV4hR9vwNlgpHA==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:IIqqKhMP98IlyJOXLaQhm8F3QNJxeECylj4yXInPkatR6vRIGuDFQvim3Q==,iv:UKMqvZhiMsfqFncleZW3UeMa9VQyQiKy2g7e5kqJfvY=,tag:xTiuJBidA5vq/K/SA5WUeQ==,type:str]
    SESSION_SECRET_KEY: ENC[AES256_GCM,data:S6wrdX5hsFnD7PBtULPnCi3bwX1EuK/j/hbsU0jF9hHHUgjWsiGkonkhsA==,iv:VibTQSXA9j/ECKqTK8S5KTq/IjyMESLxi7U2T0t6REg=,tag:eiP68JF2JLBq3lqTHUSGRA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:inWMmHh3ZNaqq6VXTQojrlVvK9jx3C0uD9Exyb7rve/9MksC0VQ/zlTYsg==,iv:DzKgxvWoZcrM2FN/0NknbttgMQpv1Y2H6/rdFhAPS4E=,tag:kLDDtfCwRkRrgutBcT/vTQ==,type:str]
    SMTP_HOST: null
    SMTP_PORT: ENC[AES256_GCM,data:hl7b,iv:bgx/tMEdExHPpxLClxL5BM3VMl9QDiiHeR724sZncME=,tag:cnqzYd9geXkr/hZsL/8ZWg==,type:str]
    SMTP_USER: null
    SMTP_PASS: null
    SMTP_SECURE: ENC[AES256_GCM,data:biPcH2c=,iv:XN1Vbx/uTfBcpRDPtbqMQ+2V0Fhz36l5Vq63bP2tNQs=,tag:phQxJg98v78qoLvGIwuPRQ==,type:str]
    EMAIL_VALIDATION_API_KEY: null
    INFOBIP_API_KEY: null
    INFOBIP_BASE_URL: null
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:q9hKHEt5vzXB1w==,iv:Q/qtpi5GbhrFdwjeiXMt7oa17lYw2wUlO7bNR1jHvzo=,tag:pmXyt6mHS98T2ELijgnK4A==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:qksUNRUC9H1UjohCBjIaanV6Fm04Cg==,iv:sNWHziAvwX+K8qN4Yy6NaECLq3vsouYXcZV/p7hKjb4=,tag:PZUt+pqic5FoA3YWoOdx8w==,type:str]
    STRIPE_SECRET_KEY: null
    STRIPE_WEBHOOK_SECRET: null
    GOOGLE_CLIENT_ID: null
    GOOGLE_CLIENT_SECRET: null
    TWITTER_CLIENT_ID: null
    TWITTER_CLIENT_SECRET: null
    ELASTICSEARCH_ENDPOINT: ENC[AES256_GCM,data:PUbUwnQkKechY1Jggb+f8Hc2OlWYw0I1Hg==,iv:olTA5w0SLbGYCQPVnnxaN/DXg7jSZ/jLUYPB0k9OrJg=,tag:zSXKohQICeg6X5egjm/3lA==,type:str]
    ELASTICSEARCH_HOSTS: ENC[AES256_GCM,data:POn1cuMlSh+4InKIvk4pCNEsmy2czhFgaA==,iv:LpXB3Lcg2oLj5agthb2xdWu+RfbknjHrtf8mO5Ql7PA=,tag:xh9zOMb3gin7qZRl0fYqMg==,type:str]
    ELASTICSEARCH_API_KEY: null
    KEYCLOAK_PUBLIC_KEY_PEM: null
    INTERNAL_SERVICE_TOKEN: ENC[AES256_GCM,data:/24SL8R/VIz9xbREVaowbWR+6ledEl2KI8fg2M4oN2E=,iv:GZyEqIjzFfu9O6XlwLcHrV7nwXgnrqa3jVtNsSVDOY4=,tag:VKMakxfeXZMcqqFvfSWdCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNjhCaWlxVm00N05qYjQ0
            WEk0S0JNQmgzRkFjSTd6NWNEZXBnUzI2cjNFCkJWMVlib3ErTTQxME9BK1BTendV
            R3l2amlLeHFxYnFiSEZvSTZQNC9oRmcKLS0tIGtpdG5nNG9Va1RXY2svVHUwY3hx
            MmVwVmZUWm5XZFhmU1VCeDhnUVpFTkkKs3EljFvRzmQ8ljgwvSKEKPO09drOPN/4
            uLglzcM2KtdItI/H0H6Hkbrhel+ch7KKGZQfKD+vkPlqcuFylcF7xg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1slytfaf55d75qg2yfeehd8eycd5gewtw370ved303g6zqeesgcrsl5uu8t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T12:50:27Z"
    mac: ENC[AES256_GCM,data:ewCfx0dMKrQ/pqpOnNSI510LwAP6u9yo93+drF001TuO34ZohqBcw/uC9q6hsv/FxzhqTFI7hmOsg6oa1I2/lM496TI+9rNIfakTPUCeAiKBk0LouL6EO9ibpW/qsabDFX5wFxQ0QSC5pvqu+p6zSjxo0J0XD7znJHdOGyS2vX8=,iv:PkUYLhVEtIfcKN3rtNpBs9nAez9lcInsIVxhJsfsaYk=,tag:KbGFYI16PYz6/CazjSZ3Sg==,type:str]
    version: 3.13.3
