apiVersion: v1
kind: Secret
metadata:
    name: api-secret
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:L+tohTpzCyT8oFGFuopr+g==,iv:CRnKZs5MpKMGOr3BdoR3bvbBEpzbSTQs/WDLXwwKxPc=,tag:bEke5ZQ+kGmsuPx184h/ZQ==,type:str]
    MONGODB_URI: ENC[AES256_GCM,data:E0LtnkJTS14APTEctD1jMEbqK1IPnAz5tQxTNZ1tcWDK6SywfmnqLC8e+I8=,iv:W7+QxxkEcVn0Wk7zctBb0XuzFQ4TWoVzzaT3G77+KM4=,tag:eER2ZYKJ69eMBbAp993Bcw==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:2aLY31cRZoD2EroBAVF3kxnZw7VJH8uj1ud7GnfE8Vmbh6yWJcajaorwVA==,iv:1PpBcTgMCgIkyw01obDfct73Kaai2xQDMG2BxH5WuuA=,tag:gcf5R4oBDVm6IePu0p8V4w==,type:str]
    SESSION_SECRET_KEY: ENC[AES256_GCM,data:NL62e42l1zwBTPa9puYq+iNSou5jcL5xzHL8lMpMAu7K5dxxG8f0iT/dQA==,iv:+CMSUTPgraWxRNt9Ha743QCLwRLzleRILWM9P0EeVTs=,tag:C79+Z3XcCDlNtFNE2hx3ig==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:0aKQF0EkWkHXphb/+COPlQsGMiZUSgA7omJr6OT5wJDpu+3+MuqKqB88Xg==,iv:/yU2iBsT9JoxgCsc9PXo772RCWdp0RrgptF7XP6vHS8=,tag:wwq4EGhieUe8GjAJW4XoJA==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:B/PZ7mYZBA==,iv:KocOuFyqEusarp6wTB47jeEsjUOrgclTpYXZ8R2tVRU=,tag:xJs+DcjTKVV+E9kVBr8XZw==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:tuQq,iv://Htu1I2rq9crGLcB99gojiKnlr5Dgz+QqgeLNXAGkg=,tag:kejRTpN0CMTQJFuSZC7Y3g==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:Nl744qnVP1Ic,iv:PoxFnZqV7lJdBNb1yCcA7TiB5vW/M7e22lL1C4RHAJM=,tag:Xgn1X4jO9Gpk/NM94em6OQ==,type:str]
    SMTP_PASS: ENC[AES256_GCM,data:njs7KPKQFdKL,iv:alAbZBpF9ywDV4aLXoectoI4nb7MZk2Pc3uyrEHfbGM=,tag:uFtBimPzdraUAetLRYdQBw==,type:str]
    SMTP_SECURE: ENC[AES256_GCM,data:yG6JZno=,iv:YhUpk9beFbSCNDVu3DhgLf9iyUHWQKMt6ocHNMTFdtE=,tag:x2fiEUdJRRqUPJTVtFK3zA==,type:str]
    EMAIL_VALIDATION_API_KEY: ENC[AES256_GCM,data:OXfffEN86AzDP9od4xcP6A==,iv:XBTxvx98bLgL94rtiMXb/d/oCOBZduc6EdRMk5z6oI0=,tag:PDsUVPKWWIRV3Ef5E3AHgw==,type:str]
    INFOBIP_API_KEY: ENC[AES256_GCM,data:LQbTSPRVRfnPmjes3v1vZA==,iv:QcaXJrQe7MlVw/hGMV/yJ4L2w5WUFcCLmow6B0kkVfA=,tag:NVokCHzdFxmWR7Cv4Kqgkw==,type:str]
    INFOBIP_BASE_URL: ENC[AES256_GCM,data:sEy/L5khlP2bk1E6FpH2Sl4T8DdX,iv:tsLA7vMtXsRGTV9q4yu/Hze3TANAo5VZxWxiSSEdrO4=,tag:EjF+973IFutH4YNgXxS7PA==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:ZJ3KBTpaycA3aw==,iv:NE6Ud3sd12fnpK9qM3zA/emKLwn3cJ8HeJVJpTiBKVQ=,tag:qp6JCCdSsWBxt+sjiNDkBA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:JJkEKB0Elc+f/PYSY12PyrYHSAlGVg==,iv:+LP1ICJhO9yQX+8d7UmspI27RyfI2ppsGHAoVEEar4c=,tag:5iJkFPY+Zm8SJvpEVE2iYw==,type:str]
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:R7YvXE0IW5FJOMZ4RXiNJ+0=,iv:v3yOv/711GIOkrkUnZmKjkF5IiFtvhxjEboZPqlqLJo=,tag:rEw79WagwzOW8vbMZkV28g==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:arsO4JVwCve5yqCU48hY,iv:wzfkrkzA45qsKw9hJaqSj5dmDIRF5CtYSrPedapXw20=,tag:19tbGD5ShQYXIzVcaFgk8A==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:5Uj+WUxvfH+LJXKKWC9cZg==,iv:lYwWn+01Z6sxukfYv3+9ehbnNs9qYg2+oyilG/KHaF0=,tag:2X56X1ulqyBL1JIif5qLUA==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:t0idLAAfMtG211Fuzqci8Q==,iv:QZNX4M0gxM5wDZ8JEI9yIDH6/Pl4iUjHGv4g67xmiJI=,tag:PRTpa+9WFxk1szJ/23xfvw==,type:str]
    TWITTER_CLIENT_ID: ENC[AES256_GCM,data:1CT212/xiKFmmFG1Mskrtg==,iv:XUE3eDxwCWYykKKvbqFd41Oa8YbAphA+E+5glQwZLfo=,tag:YuPvqfx7nLSvSnD1g2tDSA==,type:str]
    TWITTER_CLIENT_SECRET: ENC[AES256_GCM,data:GvBYw/ZiGhxWDRM+tn+ekg==,iv:AeJGpfsnF8pRSzsUWx8alZ4AqC0bx57AcohyLIY7J+o=,tag:aXeYr75VON05pY9dXMAaqg==,type:str]
    ELASTICSEARCH_ENDPOINT: ENC[AES256_GCM,data:8Sfl/omIibGVNLhIqkobvoTL8OdklW238w==,iv:QetVCjpzjpWJR+bKFxWPZz4HJSWsmOFDYX5C5aAhQzg=,tag:LZCUarCgZKby0ZziaGS3Tw==,type:str]
    ELASTICSEARCH_HOSTS: ENC[AES256_GCM,data:K3FVfpgBvRCxwno35DpWM0nzPNQOsA5A5g==,iv:46DXkBaLKC6Vq1TxLkEwTAevmf8CzykJzbn0g0y5dcE=,tag:KKDG6yHSGhKvno8j/w25yw==,type:str]
    ELASTICSEARCH_API_KEY: ENC[AES256_GCM,data:7iDFE/u5JTbKk3bgLrq3Sw==,iv:a4L/rMxvnIQ+2hY79qCLb5RMjv6C3N732YZLxzfNNPY=,tag:ruguCgP9GJ8KjPVUje27RQ==,type:str]
    KEYCLOAK_PUBLIC_KEY_PEM: ENC[AES256_GCM,data:J3PjGiWM6TyAO4khTQXaIg==,iv:ALiEUrMhzOX8+N2NMmkldxlUgPgcoXbaLQhJ8jZcwO4=,tag:YWVCLZ1blW03VxD/oLXnCg==,type:str]
    INTERNAL_SERVICE_TOKEN: ENC[AES256_GCM,data:uiEEQo+dBZG7syYhS7osk/nSfhgbSCN3AN5iV2Bq3uE=,iv:tRHdazLlkMRi4rk641rug62XgmlJh3xWIDcT+HvrGro=,tag:XRAwJZFsiMAiLcmGS0mCrQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SmNVYWxtNU5HQm9kWDlX
            c2YzKzFrNXR3VktMczEzdkJqbG1oU2ZXSzN3CmNwWUxETyt4MkQyTWs1SGdlYjl2
            aHpXR3BPQ3NzYXFxeXc1Z2JWdUdSR00KLS0tIC8xSWNyZnBvWlZqSlJDNzFNaGM0
            R3M1SWszcE8waVZpTVZPaVkrUDkzalEKitOhEF/ANGNCq9xi3JLntEMCsP8Dpe3U
            NNpEBvoreDCweaKgCU9CnBa7Vym8q1JQXA7dg39Csw/nS6iRLb/e5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1slytfaf55d75qg2yfeehd8eycd5gewtw370ved303g6zqeesgcrsl5uu8t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T11:59:04Z"
    mac: ENC[AES256_GCM,data:C6NLd1BVf9PUNJe5XoF8WY3Lo5Oq5GI5vxOhn6HB9Po/547e9RC9Yz5AgkXKDO4In25tpROS0w20tWMI+kMOOZapBkBp2nUL5ADDJ6Yi2Piw6BPlT7IYDWalCzpqW4oS+47g6WQvYntGgbMaz5rdATqz1mMIQiAfTf52Ag2zkKo=,iv:YOzlgxZsF9z29ZkgSDr4wZObGA+hIV//+0Z7iNUu0BY=,tag:IqXKav12wUJ0BYem1jv+hg==,type:str]
    version: 3.13.3
