apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:UH3esBsE3LWjbA==,iv:fxIoPHXYJBK7CLdbKyXUuiHhU7Tz9RKDSq0alukRnrk=,tag:SzHOyZBUZhYdeAXKJ2ad6g==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:YCVe/NzRaK1o/hKDoJTTA3dApmk+2g==,iv:cH+0goSIPa2U0N5f6lGS4A/eq13LKKsDZHU7jeP00xk=,tag:Wk7PtxfkzXF8mOTs1MzViw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRXh5emVaZmU2dXJBNlJh
            d1BjOVdTL2tOS0lWeCt3TkdDcEhXb211TFZjCmR0cTg3WktKQm8wUFYwd20vYXha
            ckNZSHE1U0RURm4xYjhUeFdsU2cyL28KLS0tIGNHSlNnZ2ZqV2M4WFNKbGtUZ2Y1
            WjdXVm00a0lUNTNyUjljQXB1SUdiNVEKsdXZHqW2rsm5fPcRNRV1+hpNh++eORLJ
            pZsoHn+q567GgS00Uhy2wvDTfRoDrTUt9JMYNjeo1Th1MxPEpwfQUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1slytfaf55d75qg2yfeehd8eycd5gewtw370ved303g6zqeesgcrsl5uu8t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T12:50:27Z"
    mac: ENC[AES256_GCM,data:Sp/1bba1vCtfVSvGtB8EMX0+ufCZHeDarceDW3PB+YkdhbUqwDz7OvuRjlBTj8HIU/GnsvNlkSUPDAcUGwp5v1E0CkNpN7PdToS0fvKo0z7tOliN7PTBQXj9i3k/NjpCALAaeq8gyqqxOg9VoXzXvZ4VwMlSShrGS8gVpGAcusg=,iv:AF3kNulcOWQZezKBT7uHZJoenFV6X18SFljzzaWs7rc=,tag:ziHdXwhZuNKZQQsJJIHm/w==,type:str]
    version: 3.13.3
