apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:HIXf5048mkxaVg==,iv:+NbvdlQ929vV8+7gZEvkN17bb/6oHfzGLaQdIEVgkEg=,tag:Tj4qCaT5P7JBmzdA3JzG/A==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:PRgM7ksEQ6q2czvFIe/b3vz7mN6IWQ==,iv:Dm1OB2502NPlPWAnakRiC9BJFH2I35GRtU0o/G+xYls=,tag:h/XeSYb8/JvT67flZAynqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzR0VKcGVYWGtEWmFkSnVm
            WTRrL2s3SDdsMEdPMVB3TndVT0NoYU4rQ0RvCldXMERWV2xQV1diY0x1M21YQm1M
            UnZOQXhJZWpLYlVJWU5WTHVjYUdtclkKLS0tIDk5NytvZWNLWmhDZEJJcG1JQlJq
            bW9VTnJUWGtwZGtGREl1aDVPbEdMVUEKJnuZ6yieXbpVfk9+pFWs2ktTnTGK/o7v
            klYD3KjalZe3vwIpN1ifiSIZ32+AgKFWovtUtSYfuvm7k5IZ1seKTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1slytfaf55d75qg2yfeehd8eycd5gewtw370ved303g6zqeesgcrsl5uu8t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T11:59:04Z"
    mac: ENC[AES256_GCM,data:Z3OiM9kl6Sbt+BO9fCpwnzLxSvdcehFMw+6DPUQF1Nmx6yVSjSC1vVQHBu4pqpvJsrWPwgy8ncHp6vUBTY/LIShXRSwZgyXP2UtBjsCgdDaFNLj1NYkv5QJ9Dqn27TovlGTErZnGUdErE5HJHFBm2K0swSlwBEhCILvWCw7LtpE=,iv:HuMBkBYqsFTVa8fo/4pbwUA1oR05f8d0GL9N0FMjTiA=,tag:uIzUfZuEXmFh+kwfOB9J1w==,type:str]
    version: 3.13.3
