module.exports = {
  testEnvironment: 'node',
  coverageDirectory: 'coverage',
  collectCoverageFrom: [
    'controllers/**/*.js',
    'services/**/*.js',
    'repositories/**/*.js',
    'utils/**/*.js',
    'helpers/**/*.js',
    'middlewares/**/*.js',
    'validators/**/*.js',
    '!**/node_modules/**',
    '!**/seeders/**',
    '!**/migrations/**',
    '!**/index.js',
  ],
  coverageThreshold: {
    global: {
      statements: 80,
      branches: 75,
      functions: 80,
      lines: 80,
    },
  },
  testMatch: ['**/__tests__/**/*.test.js'],
  testPathIgnorePatterns: ['/node_modules/', '/coverage/', '.babelrc.test.js'],
  setupFilesAfterEnv: ['<rootDir>/__tests__/setup/jest.setup.js'],
  moduleNameMapper: {
    '^@controllers(.*)$': '<rootDir>/controllers$1',
    '^@services(.*)$': '<rootDir>/services$1',
    '^@repositories(.*)$': '<rootDir>/repositories$1',
    '^@models(.*)$': '<rootDir>/models$1',
    '^@config(.*)$': '<rootDir>/config$1',
    '^@utils(.*)$': '<rootDir>/utils$1',
    '^@helpers(.*)$': '<rootDir>/helpers$1',
    '^@middlewares(.*)$': '<rootDir>/middlewares$1',
    '^@validators(.*)$': '<rootDir>/validators$1',
    '^@constants(.*)$': '<rootDir>/constants$1',
    '^@adapters(.*)$': '<rootDir>/adapters$1',
    '^@interfaces(.*)$': '<rootDir>/interfaces$1',
    '^@queues(.*)$': '<rootDir>/queues$1',
    '^@workers(.*)$': '<rootDir>/workers$1',
    '^@socket/(.*)$': '<rootDir>/socket/$1',
  },
  testTimeout: 10000,
  verbose: true,
  coveragePathIgnorePatterns: ['/node_modules/', '/coverage/', '/__tests__/'],
  transformIgnorePatterns: ['node_modules/(?!(@faker-js)/)'],
  transform: {
    '^.+\\.js$': ['babel-jest', { configFile: './.babelrc.test.js' }],
  },
};
