apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
data:
  NODE_ENV: production
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_USER: travelnest
  DB_NAME: travelnest
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_DB: "1"
  NATS_URL: nats://nats:4222
  NATS_STREAM: TRAVELNEST_ANALYTICS
  NATS_CLIENT_NAME: travelnest-worker
  MONGODB_DATABASE: travelnest_analytics
  MINIO_ENDPOINT: minio
  MINIO_PORT: "9000"
  MINIO_BUCKET: uploads
  MINIO_USE_SSL: "false"
  WORKER_HEALTH_PORT: "4001"
  REDIS_USERNAME: ""
