apiVersion: v1
kind: Secret
metadata:
  name: worker-secret
type: Opaque
stringData:
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_PASSWORD: ${DB_PASSWORD}
  REDIS_HOST: ${REDIS_HOST}
  REDIS_PORT: ${REDIS_PORT}
  MONGODB_URI: ${MONGODB_URI}
  MINIO_ENDPOINT: ${MINIO_ENDPOINT}
  MINIO_PORT: ${MINIO_PORT}
  MINIO_BUCKET: ${MINIO_BUCKET}
  MINIO_USE_SSL: ${MINIO_USE_SSL}
  MINIO_REGION: ${MINIO_REGION}
  ELASTICSEARCH_ENDPOINT: ${ELASTICSEARCH_ENDPOINT}
  ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HOSTS}
  ELASTICSEARCH_API_KEY: ${ELASTICSEARCH_API_KEY}
  MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
  MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
