apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: travelnest
resources:
  - ../../base
  - configmap.yaml
  - secret.yaml
  - ingress.yaml
images:
  - name: travelnest-api
    newName: docker.io/your-dockerhub-user/travelnest-api
    newTag: latest
