apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
stringData:
  DB_PASSWORD: ${DB_PASSWORD}
  MONGODB_URI: ${MONGODB_URI}
  SESSION_SECRET: ${SESSION_SECRET_KEY}
  SESSION_SECRET_KEY: ${SESSION_SECRET_KEY}
  JWT_SECRET: ${JWT_SECRET}
  SMTP_HOST: ${SMTP_HOST}
  SMTP_PORT: "587"
  SMTP_USER: ${SMTP_USER}
  SMTP_PASS: ${SMTP_PASS}
  SMTP_SECURE: "false"
  EMAIL_VALIDATION_API_KEY: ${EMAIL_VALIDATION_API_KEY}
  INFOBIP_API_KEY: ${INFOBIP_API_KEY}
  INFOBIP_BASE_URL: ${INFOBIP_BASE_URL}
  MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
  MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
  STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
  STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
  GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
  GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
  TWITTER_CLIENT_ID: ${TWITTER_CLIENT_ID}
  TWITTER_CLIENT_SECRET: ${TWITTER_CLIENT_SECRET}
  ELASTICSEARCH_ENDPOINT: ${ELASTICSEARCH_ENDPOINT}
  ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HOSTS}
  ELASTICSEARCH_API_KEY: ${ELASTICSEARCH_API_KEY}
  KEYCLOAK_PUBLIC_KEY_PEM: ${KEYCLOAK_PUBLIC_KEY_PEM}
  INTERNAL_SERVICE_TOKEN: ${INTERNAL_SERVICE_TOKEN}
