apiVersion: v1
kind: Secret
metadata:
    name: notification-secret
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:9KNN80BtcW+wpO1AsARAsQ==,iv:lqYPTUYBs5TN2WtGKgCT42LaLvz8vx72e5aytJe4vl8=,tag:OSaRMDKGGQY8RbCud2lmyw==,type:str]
    MYSQL_DSN: ENC[AES256_GCM,data:Tdm2wzzYsJDe/axutnCbTeFnZS9HJLt/7GeGCyKHiuuzd6xI0tkPg90yJyEcfBHr4rhzSmajrVkwBmB0HGXcWu6+iDam,iv:8ve7afqx37lvgL9AVApKdj06RcoZHF0rLhjKJJkM1RY=,tag:89Z0rGzcm8s3EWGN0D7H1A==,type:str]
    SMTP_HOST: null
    SMTP_USER: null
    SMTP_PASS: null
    INTERNAL_SERVICE_TOKEN: ENC[AES256_GCM,data:erJ5tq0k+kyOlbEDDnOi8A/0f2e7xmf6m1szqmRGKnI=,iv:g6MflsQ11hAQNUGfWCMzNfYXfd6CSeH2bkgeyFESMjg=,tag:wij/nok66CvQTEB4qYRahA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRzVUWDF2U2FzMDNLazdN
            M2EwM0s4WGpiaEdDYnFWSzEwbU4vYkZmaUNjCmtUZkZmajV3Qjdxb3pybEV2RGlP
            TUhzSTNpcWtCeTN5ZUFrbzZWcmQxaTQKLS0tIFYxQzVUSEkyNTRvMXA2RzgvaHFX
            cGpCUXdMVlJZN3FVMGlMSEJ6VWtJQTQKrjFCB1IykzWAvS3JMPhjaL6AHiXMsTzx
            f6l3l+P7K9k25v70jZwNtjyOmKNkNwL10b8ZuHODx30OZt4dmqVZdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1slytfaf55d75qg2yfeehd8eycd5gewtw370ved303g6zqeesgcrsl5uu8t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T12:50:27Z"
    mac: ENC[AES256_GCM,data:r8nc6H5lCryS2ExielE73NdV8SX4FJ+s9GpLnRr7XYSXTuDP7UJu7T8qhb8/dF/PEyegHUzySZmlpsDOghLHG8pHSnBc+ap9bk7n0YcKcukUrziaihEt977LG6Z1IZOppv69p/BGKvaIuTAcR/sChUYVt5QvZDpVZ72/Sa1os08=,iv:7oSXQQvsg7eeM1sfUMGduqx3Ci+QVwUuPf/HAbeNleM=,tag:D7KN6q9VCRW47gB8MBV32A==,type:str]
    version: 3.13.3
