apiVersion: v1
kind: Secret
metadata:
    name: notification-secret
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:ealB4w7nHeYZ0+Roi9egjQ==,iv:upGiaITLHRNEgfeXxj0d5sVksJMsccJzLnHA7U+aR/o=,tag:nFeMkR81YieAyl09PRqM9g==,type:str]
    MYSQL_DSN: ENC[AES256_GCM,data:A+I603OWy9CuNrI3mzWr8AJKt3cA0O3cVlsIdZHvOaxgCZJZ/8slFqiLpBZsTlg96IZfOTXyHaPZOClVT/qsRm4aNqxz,iv:aKiv+pCOKrBGTks8jopVGRhcV14Bx5/bKL3ui1NXxq0=,tag:QvA0wG09kaLh5fo0w+8mNQ==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:4wnZfUsHGA==,iv:FGuxPojIesJHcaIEKEw8bbQ0vr47ksNkmWakCRlpT/g=,tag:yz+8km4smAGcFF9HwRPgDg==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:H/CQttrG4bQl,iv:d2eyk25Yom80BUTpltnnelDNtS/WUK+LNKdcMxM0FgM=,tag:xYZbXWvZZJuU1Mxr+Xjq3g==,type:str]
    SMTP_PASS: ENC[AES256_GCM,data:XBRJknMSLEBr,iv:+02NHVRIARO2BWvXJUA2/AwEzj+U+ucrD1YvP9nBE0E=,tag:rmG0DB3uKPUc8yTAxghGnw==,type:str]
    INTERNAL_SERVICE_TOKEN: ENC[AES256_GCM,data:Mz2QcxPt+QV7Gh9GAr3SSlQHI7L7j3YBMAh0XMsgRwU=,iv:cWd18OdabjiMwl6AsGjgzm0H+0djEy0iDxoUIbkOE9g=,tag:oKaaNOwZJYB8N/9dSXRzGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYWg2YVBrbGVNQmpxQzRt
            NVpnQzh3U3FDSE1ZNmUwUnBvTTZxcmROV2w0CkxoSElFeEpPSmIweVhvMHllR1VN
            R1BTeStOYTJHd0ovbkt5MURDTzZzaWcKLS0tIDBnL3lNYk9qTHBPSmJ5SEpiTm50
            Z2p0U3UrWHRqYlpQWkYvLzdvbmN5WWcKQOoFxtvV0+dG/O9RpkWQN0B/P4cZl5tq
            l5qd47X82VAJ8m8tzLAoZzX340S85gUC/W6DGO5OluHArAJzsKHsoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1slytfaf55d75qg2yfeehd8eycd5gewtw370ved303g6zqeesgcrsl5uu8t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T11:59:04Z"
    mac: ENC[AES256_GCM,data:3aX+GnwEKmf5aq8ddF489HIZXfQsA3T1Em2jXUBvS3Gv6dQPkmCevgPTZ/3kzh3K55/Wl/SXk7gavFNreU96lJS+OebkZ0LDE6jNlZWLpL4cZLjTyCo2NYqRyN8e9Cy0nBGnHd00+JvlZS6NLphLas5NmDSGXeKor1jadXcYj8Y=,iv:dRn2qb3CxIQvEM5+cyZwKJiCBVD3ksu4JSZMx5GVaBM=,tag:elpnKSW8L54LKccZ6N/y7Q==,type:str]
    version: 3.13.3
