apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: travelnest
resources:
  - ../../base
  - ingress.yaml
images:
  - name: travelnest-admin
    newName: docker.io/leducphuong/travelnest-admin
    newTag: latest
patches:
  - path: service.yaml
  - target:
      kind: Deployment
      name: admin-client
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/containerPort
        value: 3000
