apiVersion: v1
kind: Secret
metadata:
  name: media-secret
type: Opaque
stringData:
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_PASSWORD: ${DB_PASSWORD}
  MYSQL_DSN: travelnest:${DB_PASSWORD}@tcp(${DB_HOST}:${DB_PORT})/travelnest?parseTime=true
  MINIO_ENDPOINT: ${MEDIA_MINIO_ENDPOINT}
  MINIO_BUCKET: ${MINIO_BUCKET}
  MINIO_USE_SSL: ${MINIO_USE_SSL}
  MINIO_REGION: ${MINIO_REGION}
  PUBLIC_OBJECT_BASE_URL: ${PUBLIC_OBJECT_BASE_URL}
  MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
  MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
