apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  MYSQL_PASSWORD: ${DB_PASSWORD}
  KEYCLOAK_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
