apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - project.yaml
  - apps/infra-mysql.yaml
  - apps/infra-redis.yaml
  - apps/infra-minio.yaml
  - apps/infra-nats.yaml
  - apps/infra-keycloak.yaml
  - apps/app-analytics.yaml
  - apps/app-media.yaml
  - apps/app-notification.yaml
  - apps/app-api.yaml
  - apps/app-worker.yaml
  - apps/app-frontend.yaml
  - apps/app-admin-client.yaml
