apiVersion: v1
kind: Secret
metadata:
    name: keycloak-secret
type: Opaque
stringData:
    KEYCLOAK_DB_PASSWORD: ENC[AES256_GCM,data:mm8BZt6GDMNf2XRiduplnw==,iv:Yo+mq+Joyd59dXjTWNH5kKRE5QH5N3E1ga/aUB+blYg=,tag:WhS9cc8NF9Tnq+BzRoUVIg==,type:str]
    KC_DB_USERNAME: ENC[AES256_GCM,data:hqXkLnxAu30=,iv:JuIq7auM6m96ujo0tOTITXyMUHessjPn/+1Dlw7UJqQ=,tag:YRLUGPLRPxgyRDwrCY+CdQ==,type:str]
    KC_DB_PASSWORD: ENC[AES256_GCM,data:1v5f1mxBmen6ydxdum6cng==,iv:+obzXermiTaRIqLpTDT2qFf3gCbXhb9alLNME31lSc4=,tag:IE29OZniOhP8EtaYTaMMjA==,type:str]
    KEYCLOAK_ADMIN_USER: ENC[AES256_GCM,data:xBKyaj4=,iv:fyweCuF8ZzLtEwJbEC9Vb0o6FcAMvsXG0nrA/N5KkJ0=,tag:54wVOBXMhuptuE0YikmUMw==,type:str]
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:kgRs1kD03AwDPc+pt5Logg==,iv:ZWMeA7dF/j6hzSHmc5HBltSVD6RK4db1ku1qcSUXdJ4=,tag:3flaOAf7DEDX3qW5yJwJ/A==,type:str]
    KC_BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:I25Thes=,iv:R2Avi0nE0+gIu6be8wF9R/qIZOENDb23DMFZC4aZPr4=,tag:1vy5y4IG6sNc2Oddc77rUQ==,type:str]
    KC_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:pQ0/cXr7pCQ1FH2Xa4tGIQ==,iv:nDAXwdBg1M4rNydtKxIvtM+J9BbowZcmNqrqAzpVDl4=,tag:FTuilf0Fod5rHO1/BwFWaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbG5HRTRMbjFjWHRiTksr
            bTNpY0RXamFKY2JYcW9TanZwQ0RUVUVua1NRCllpbFhpMTI2YjBSMEZVRU1Tajhn
            NFJKK2dTL0Vobyt4OCtlNzBFeVF3WWMKLS0tIFdzbmpCVm8vV2pNaEowUzBMMGQ1
            dEFEN3o0L3krRnlaZFhZNG9QSVNNMWsKUU9jBMRRz/NUHvHMs5BzpXdVSEeGFI6w
            aa7a0bjqtRXqFfBeB5xlxhHdtbONkZPmrVNVA75P3+uOlmveN0OICg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1slytfaf55d75qg2yfeehd8eycd5gewtw370ved303g6zqeesgcrsl5uu8t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T11:59:04Z"
    mac: ENC[AES256_GCM,data:SlaA3M5ZZcAslofMgYoh8gB0Ubo1WGtWvNKTpWOjo6fTHIFdaF/HQFDigrEG3OwCnizQL9jCqZJspN+EJLCIlm8J0MDThbTGbEqegaknvx+9SVHg8qR1boCSgadOTVi0hGhrzV4IRw1h4g4pXWQNw2m4ktK6efFAIcIl2NQyn7U=,iv:1/dH9p/KOW56PgMpii6SlI/u6NnVTr+0llAmgWXPqpU=,tag:2CWQh1SUsqtee5wLuqKxcg==,type:str]
    version: 3.13.3
