apiVersion: v1
kind: Secret
metadata:
    name: keycloak-secret
type: Opaque
stringData:
    KEYCLOAK_DB_PASSWORD: ENC[AES256_GCM,data:bz+isZGVvtQ4EYdGSR8KnQ==,iv:i1bhkp/VDcOQ4HBD8aLP3/9UPmQJhvPckoR57GgRfYA=,tag:IkM0RIZopqUh0TlpgB1uTA==,type:str]
    KC_DB_USERNAME: ENC[AES256_GCM,data:b75eMoCMGeY=,iv:ZmqA6qcCKpog7XOJz2p7Ty/SWeZc2RhWGwm38ObmlYI=,tag:IxdZzAPSuruNsvClsXqokQ==,type:str]
    KC_DB_PASSWORD: ENC[AES256_GCM,data:U+5JBblDVLc01FiLe2sQTA==,iv:uYO3u7p0+Xhjt5PEtIRsr952vOVkiYjAKTdPwfxfKzU=,tag:cH/1GofwYtiCFAHO+sWVlw==,type:str]
    KEYCLOAK_ADMIN_USER: ENC[AES256_GCM,data:kDbX6FY=,iv:sChUL4ZcrkH6t7af8M/S6hm455LR1uQJQaJ+BOkXMnU=,tag:CfyOg0t29DURlDA0dcex5w==,type:str]
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:+ps166YKMBbxDzuAmYXmKw==,iv:sjcR+Prot16o9liOYQb/yIkE41zNMykKN0SI8xSuaFc=,tag:fsunvYyGCOXPkh/9eBm5rg==,type:str]
    KC_BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:hyhGX+0=,iv:koY56rzubkBA0+BhlmMp3RGkMwKPFHZ807sTped3Jy8=,tag:EldgyARd9gdfizwdYUKpqg==,type:str]
    KC_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:Pi59SJlbPCtze8KkhX/5Zg==,iv:o7yjb47uPhjv3sTLTD+eIwELiXYwFyh5RO8qrEwFPlM=,tag:NuMhXVecPA1s/JvI+bNDWg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvL0lSWVpHR1IwV3c4TElm
            NXFaSXNnQTg4RldKcENpYzQzbGZHRXJtTmxrCjZ5MDdWMjE4U3FuRkZZQmd1MU5O
            UEQ5RTBLK2tCYUFJR3dRSzExd0JqTWcKLS0tIGE4U3J0ZWtqOTBacjlSMGR0ZW1K
            eXpSZklDN1pZSTk0c2JwRlNURE1QVlUKB1+2eN9HiX/tuxoSlAdgpEM05o7tufsW
            HkroK/k3bfjKC12RYNDhGiy/PQ6xiWWoPeFB/g8ruJBzGOYWdFivyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1slytfaf55d75qg2yfeehd8eycd5gewtw370ved303g6zqeesgcrsl5uu8t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T12:50:27Z"
    mac: ENC[AES256_GCM,data:9c2VzfXp8ZlWY14GKG42/QeF2hGy1PImDclfIz4eDQGED8YBq31xpgehT++3GvSIrudoaq79Yqf0FxsHPziVuIH1BjsJfeJCI9Y9D8a8Ica8DKx8B+H2Sl1hDWBYVCMrNIAMhO/NCGg3FfaAy11h2nP4npyIw1+j2F5MM7+AeKw=,iv:DxUCEFAhr3qy8MhSsnPQwI1zLC8+iqdk9B32twWdtxY=,tag:+nM7qBu5OaWq80HdEaLtfg==,type:str]
    version: 3.13.3
